// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6n4jkRGNPE3orGLNxHiWmmcxW-1fdHMI',
    appId: '1:1057496983314:web:7e088c4360539bae9bf5cb',
    messagingSenderId: '1057496983314',
    projectId: 'todo-serverpod',
    authDomain: 'todo-serverpod.firebaseapp.com',
    storageBucket: 'todo-serverpod.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBy3jxPJZim0cjXFTboMaFFS9PfI0PIW-U',
    appId: '1:1057496983314:android:a8199bbb76ba92f09bf5cb',
    messagingSenderId: '1057496983314',
    projectId: 'todo-serverpod',
    storageBucket: 'todo-serverpod.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqwzS6BEnDw8PBTQvekClPqvxRs-A3bBE',
    appId: '1:1057496983314:ios:90880504d2b768b09bf5cb',
    messagingSenderId: '1057496983314',
    projectId: 'todo-serverpod',
    storageBucket: 'todo-serverpod.appspot.com',
    iosBundleId: 'com.example.todoFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqwzS6BEnDw8PBTQvekClPqvxRs-A3bBE',
    appId: '1:1057496983314:ios:8a695ef7deafa8f19bf5cb',
    messagingSenderId: '1057496983314',
    projectId: 'todo-serverpod',
    storageBucket: 'todo-serverpod.appspot.com',
    iosBundleId: 'com.example.todoFlutter.RunnerTests',
  );
}
